apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopazone-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shopazone-dev
  source:
    repoURL: 'https://<your-shopzone-apps>.git'
    path: shopazone-dev
    targetRevision: HEAD
  destination:
    server: 'https:/<your-kubernetes-cluster>'
    namespace: shopazone-dev
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true