apiVersion: v1
kind: ConfigMap
metadata:
  name: sc-nginx-default-conf-9090-cm

data:
  default.conf: |
    server {
    listen       9090;
    #server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    #location / {
    #    root   /usr/share/nginx/html;
    #    index  index.html index.htm;
    #}

    location / {
        
        # proxy to upstream applications
        proxy_pass http://127.0.0.1:80;
        proxy_set_header Host $http_host;

        # don't use http 1.0 so keepalive enabled by default
        proxy_http_version 1.1;

        # prevent client from closing keepalive
        proxy_set_header Connection "";

        # don't need timeouts for process to process communication
        # (why complicate things with this MITM proxy? let client timeout)
        proxy_send_timeout 86400s;
        proxy_read_timeout 86400s;

        # don't write client body to docker file system
        proxy_request_buffering off;
    }

    location /gofinance {
       proxy_pass http://127.0.0.1:8080/;
       #proxy_set_header Host $http_host;
       proxy_http_version 1.1;
       proxy_set_header Connection "";
       proxy_send_timeout 86400s;
       proxy_read_timeout 86400s;
       proxy_request_buffering off;
    }

    location /login {
       proxy_pass http://127.0.0.1:8080/login;
       #proxy_set_header Host $http_host;
       proxy_http_version 1.1;
       proxy_set_header Connection "";
       proxy_send_timeout 86400s;
       proxy_read_timeout 86400s;
       proxy_request_buffering off;
    }

    location /get-headers {
       proxy_pass http://127.0.0.1:8888/headers;
       proxy_set_header Host $http_host;
       proxy_http_version 1.1;
       proxy_set_header Connection "";
       proxy_send_timeout 86400s;
       proxy_read_timeout 86400s;
       proxy_request_buffering off;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    }
